#!/usr/bin/env python3
"""receipts.py -- keep Part A's receipt table identical to the live receipts.

WHY THIS EXISTS

Every numbered check returns a receipt string.  That string is published twice:
once by verify.py at run time, and once as a row of the Part A table in
src/tour.md (whence src/body.tex and the PDF).  Nothing compared the two, so a
receipt could be edited in one place and left stale in the other -- which is
exactly what happened to rows 27, 54 and 55, in a Part A that opens by
claiming "every line below was generated by running the suite, not by
transcription".

    python checks/receipts.py            # report drift, exit 1 if any
    python checks/receipts.py --write    # rewrite the rows from live output

The --write mode is the intended way to change a receipt: edit the string in
verify.py, run this, and the table follows.  Never hand-edit a Part A row.
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
TOUR = os.path.join(ROOT, 'src', 'tour.md')
VERIFY = os.path.join(HERE, 'verify.py')

# "| 27 | 5 | text |"  /  "| 54 | audit | text |"  /  "| 56 | c2c | text |"
MAXCHECK = 200          # no check number will ever reach a 4-digit year
ROW = re.compile(r'^\| (\d+) \| ([^|]+?) \| (.*?) \|$')


def live_receipts():
    """{check number: receipt text} straight from a verify.py run."""
    p = subprocess.run([sys.executable, VERIFY], capture_output=True,
                       text=True, encoding='utf-8', errors='replace')
    if '/59 checks pass' not in p.stdout:
        raise SystemExit('verify.py is not green; fix that first:\n'
                         + (p.stdout or p.stderr)[-800:])
    out = {}
    for m in re.finditer(r'^check +(\d+) +PASS +(.+)$', p.stdout, re.M):
        out[int(m.group(1))] = m.group(2).rstrip()
    return out


def read_tour():
    with open(TOUR, 'rb') as fh:
        return fh.read().decode('utf-8').replace('\r\n', '\n')


def table_rows(text):
    """{check number: (line index, kind, published text)} for Part A rows."""
    rows = {}
    for i, line in enumerate(text.split('\n')):
        m = ROW.match(line)
        if not m:
            continue
        n = int(m.group(1))
        kind, body = m.group(2).strip(), m.group(3)
        # Part A rows carry a receipt: the chapter column is a number, 'audit'
        # or 'c2c'.  The harmonics table's rows are prose in every column.
        # Bound by MAXCHECK: Part C's timeline has rows keyed by YEAR
        # ("| 1947 | ... |"), which would otherwise be read as check numbers.
        if n <= MAXCHECK and (kind.isdigit() or kind in ('audit', 'c2c')):
            rows.setdefault(n, (i, kind, body))
    return rows


def main():
    write = '--write' in sys.argv
    live = live_receipts()
    text = read_tour()
    rows = table_rows(text)

    missing = sorted(set(live) - set(rows))
    extra = sorted(set(rows) - set(live))
    drift = [n for n in sorted(set(live) & set(rows))
             if rows[n][2].strip() != live[n].strip()]

    print('live receipts: %d   Part A rows: %d' % (len(live), len(rows)))
    if missing:
        print('  receipts with no Part A row : %s' % missing)
    if extra:
        print('  Part A rows with no receipt : %s' % extra)
    print('  rows drifted from the receipt: %s' % (drift or 'none'))
    for n in drift:
        print('\n  row %d' % n)
        print('    published: %s' % rows[n][2][:150])
        print('    live     : %s' % live[n][:150])

    if drift and write:
        lines = text.split('\n')
        for n in drift:
            i, kind, _ = rows[n]
            lines[i] = '| %d | %s | %s |' % (n, kind, live[n].strip())
        with open(TOUR, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write('\n'.join(lines))
        print('\nrewrote %d row(s) in src/tour.md from live output' % len(drift))
        print('now run: python md2tex.py && python build.py')
        return 0

    if drift or missing or extra:
        print('\nPart A is OUT OF SYNC with the suite.'
              '  Fix with: python checks/receipts.py --write')
        return 1
    print('\nPart A matches the live receipts exactly.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
